### ISSUE TITLE
Publish release notes for services like sibbell.com?

### ISSUE THREAD

**Issue by sebrojas14** [hazzik/DelegateDecompiler#100]

**Comment by hazzik** [comment]
Never heard of them. Can I do it painlessly (automatically/automagically)?

**Comment by sebrojas14** [comment]
Yes, you only have to put the release notes in the GitHub versions, currently you don't have it
![image](https://cloud.githubusercontent.com/assets/1771574/24303485/31b23f96-1084-11e7-9b7f-cf2269a4daaf.png)

**Comment by hazzik** [comment]
Ok, not really interested of doing so. I'll try to publish releases on github though.
