### ISSUE TITLE
DbFuncions

### ISSUE THREAD

**Issue by dmostert** [hazzik/DelegateDecompiler#101]
I'm not sure if this should work:
`[Computed]`
`public int Days => DbFunctions.DiffDays((DateTime?)DateTime.Today, (DateTime?)LoggedDate) ?? 0
`
(LoggedDate is DateTime)

I get the following exception: 
`System.NotSupportedException: 'This function can only be invoked from LINQ to Entities.'`

Which is expected, but looking at other issues, it would seem that DBFuctions should work?

Or any other options to get this to work?

**Comment by mayorovp** [comment]
You can write you own function and mark it with `[DbFunction("Edm", "DiffDays")]` attribute

**Comment by hazzik** [comment]
I think this is outside of scope for DD. So closing.
