### ISSUE TITLE
Exception occured as "Argument types do not match"

### ISSUE THREAD

**Issue by jxw00100** [hazzik/DelegateDecompiler#107]
Hi,
I recently using this wonderful package in my project. However a error happened and blocked my developing. Here is the exception detail:

> System.ArgumentException was unhandled by user code
>   HResult=-2147024809
>   Message=Argument types do not match
>   Source=System.Core
>   StackTrace:
>        at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
>        at DelegateDecompiler.Address.Merge(Expression test, Address address1, Address address2, IDictionary`2 map)
>        at DelegateDecompiler.Processor.ProcessorState.Merge(Expression test, ProcessorState leftState, ProcessorState rightState)
>        at DelegateDecompiler.Processor.<>c__DisplayClass14_0.<ConditionalBranch>b__0()
>        at DelegateDecompiler.Processor.Process()
>        at DelegateDecompiler.Processor.Process(VariableInfo[] locals, IList`1 args, Instruction instruction, Type returnType)
>        at DelegateDecompiler.MethodBodyDecompiler.Decompile(MethodInfo method)
> 
>   InnerException: 
> 

After looking deep inside your source code, i guess the problem is caused in this method "internal static Expression AdjustType(Expression expression, Type type)".

Actually, in my case, with the method:
Address Merge(Expression test, Address address1, Address address2,  IDictionary<Tuple<Address, Address>, Address> map)" 

the right expression's type is not same as the left expression' type, but is a derived from it. I believe after the call of "Processor.AdjustType", the derived one should be convert (call Expression.Convert) to the other one which is the base type. However, it seems it did nothing after calling "Processor.AdjustType" since both of their types are referenced type.

Can you please have a look?
Thanks.

**Comment by jxw00100** [comment]
I tried add following code in the end of "AdjustType"

if (type.IsAssignableFrom(expression.Type) && expression.Type.IsClass)
            {
                return Expression.Convert(expression, type);
            }

And then my problem was resolved.
Hope my words make sense for you

**Comment by hazzik** [comment]
Thanks, I'll take a look when I'll have time.

**Comment by hazzik** [comment]
@jxw00100 can you provide a sample code which you are trying to decompile?

**Comment by jxw00100** [comment]
The original code is complicated and has many sensitive business logic.
I will try to provide you with a simple one later if I made it.

**Comment by NetMastr5** [comment]
I also get an Argument types do not match error on 1 query that uses decompile, but only when running resharper code coverage.

Other decompiled IQueryables work without issue, as well as the query in question when not running code coverage (debug or non-debug).

I have not tried jxw00100's source code change to see if it fixes my issue as well, as I have not had time, but wanted to post details on reproducing this error message, even though the stack trace is a bit different.  I am running version 0.23.0 for reference.

[stack trace.txt](https://github.com/hazzik/DelegateDecompiler/files/1480042/stack.trace.txt)
[Unit test.txt](https://github.com/hazzik/DelegateDecompiler/files/1480051/Unit.test.txt)
[Method being tested.txt](https://github.com/hazzik/DelegateDecompiler/files/1480055/Method.being.tested.txt)
[GetById2 method definition.txt](https://github.com/hazzik/DelegateDecompiler/files/1480061/GetById2.method.definition.txt)
[Entity definition.txt](https://github.com/hazzik/DelegateDecompiler/files/1480067/Entity.definition.txt)

**Comment by magicmoux** [comment]
No follow up on this case ? 
I could try to include @jxw00100 fix in PR #114 if it passes the tests harness but, if possible, specific unit tests would be welcome anyway.

**Comment by magicmoux** [comment]
Deleted my previous comment, since it came from a mistake on my side.
Sory for the disturbance and best wishes anyway.
