### ISSUE TITLE
Decompile DateTime to play with ToUniversalTime and ToLocalTime

### ISSUE THREAD

**Issue by nawfalhasan** [hazzik/DelegateDecompiler#115]
Say I have a DateTime property coming from DB which is in UTC. I would like to display it in local time in front-end. E.g.

    public partial class Order
    {
        public DateTime OrderDate { get; set; }
        
        [Computed]
        public DateTime OrderDateLocal => OrderDate.ToLocalTime();
    }

My EF query would look like,

    IQueryable query = new NORTHWNDEntities().Orders.Select(o => new { o.OrderDateLocal }).Decompile();

I would like subsequent `OrderBy` and `Where` on `query` to be based on `OrderDateLocal.ToUniversalTime`.

The advantage of [ToLocalTime](https://msdn.microsoft.com/en-us/library/system.datetime.tolocaltime(v=vs.110).aspx) and [ToUniversalTime](https://msdn.microsoft.com/en-us/library/system.datetime.touniversaltime(v=vs.110).aspx) are that they take care of DST conversion if any.

For e.g. my query,

    var filtered = new NORTHWNDEntities().Orders.Where(x => x.OrderDateLocal == new System.DateTime(1996, 7, 4)).Decompile().ToList();

fails with

> An unhandled exception of type 'System.NotSupportedException' occurred in EntityFramework.SqlServer.dll

> Additional information: LINQ to Entities does not recognize the method 'System.DateTime ToLocalTime()' method, and this method cannot be translated into a store expression.

I could achieve _somewhat_ by doing this:

    public partial class Order
    {
        public DateTime OrderDate { get; set; }
        
        [Computed]
        public DateTime OrderDateLocal => DbFunctions.AddMinutes(OrderDate, someOffSetValue);
    }

but this doesn't handle DST as far as I understand.

**Comment by hazzik** [comment]
This is not in the scope of the DelegateDecompiler. The problem is that EF does not support these methods.
