### ISSUE TITLE
NotSupportedException when decompiling assignment `x => x.Value = 3`

### ISSUE THREAD

**Issue by mycroes** [hazzik/DelegateDecompiler#117]
When decompiling a simple assignment (`x => x.Value = 3`) a NotSupportedException is thrown from `Processor.BuildMemberInit(...)`. I was wondering if this behavior is intentional since the C# compiler doesn't actually allow you to type this as expression either, or whether it's just not supported because there was no demand.

I don't see any reason why it would be hard to generate the BinaryExpression that performs the assignment (at least for simple assignments), so if there's no reason to avoid it I can implement it...

**Comment by hazzik** [comment]
This was a mix of both reasons.

**Comment by mycroes** [comment]
Thanks for implementing this!
