### ISSUE TITLE
Can we enforce C# behaviour on the SQL SUM operation?

### ISSUE THREAD

**Issue by IronSean** [hazzik/DelegateDecompiler#118]
In C# when you use `Sum()` on an empty set, it returns 0. When that converts to SQL it returns `null`. So if you have a property like this it will return NULL on the SQL query even though in C# it calculates a value:

```csharp
class Order {
    [Computed]
    [NotMapped]
    public decimal OrderTotal => OrderItems.Sum(i => i.ItemTotal) 
        + AdditionalFees.Sum(af => af.Fee);

    public virtual ICollection<OrderItem> OrderItems { get; set;}

    public virtual ICollection<AdditionalFee> AdditionalFees{ get; set;}
}

context.Orders.OrderBy(o => o.OrderTotal).Decompile().ToList();
```

**Expected**
If either set is empty, the result will be (Sum1 + 0) = Sum1 and the list will sort by OrderTotal. Sorting in Memory will achieve this.

**Actual**
In C# the result is Sum1, but in SQL the result is NULL, so a filter or order operation will behave weirdly because elements with empty sets are sorted as if their value was `null`.

**Proposed**
Changing the computed function to something like this works: `OrderItems.Sum(i => (decimal?) i.ItemTotal) ?? 0`. casting to a nullable decimal allows you to add the `??` null coalesce operator, which translates to a check in SQL to return 0. This is probably only safe in non-nullable columns. Does this seem like a sensible approach for the Library? Enforcing that the compiled SQL behaves as the source C# does to achieve uniform results between in memory properties and decompiled SQL queries?

I could possibly even attempt to do the PR for this, if it's an acceptable approach.

**Comment by hazzik** [comment]
This will require a lot of work on our side. I believe that the linq provider should emit the SQL that matches the Linq-to-objects semantic. If this is not supported by your linq provider you need to make changes to your method.
