### ISSUE TITLE
Issues found in 0.24

### ISSUE THREAD

**Issue by magicmoux** [hazzik/DelegateDecompiler#121]
Hi @hazzik,

using more complex type hierarchies and overriden member/methods than proposed in the tests, I noted some issues.
In my tests I extended the animal hierarchy with Feline->Cat subclasses, overriding the Species property
and introducing an (also overridden) IsAdoptedBy method to the Animal class.

First, I noticed that the new TypeHierarchyComparer class implementation does not work properly with the .NET collections' sort algorithm. My diagnosis is that falling back to name sort is the issue here because it makes unrelated items "comparable" in a way that is not related to hierarchy flattening (I understand that the fallback comparison was set to make the results predictible but) so the sort is finally inaccurate.

Second, bravo for the introduced DecompileConcrete and DecompileVirtual methods, it's much more simple and elegant than the solution I previously tried to implement 
However, I observed that it still doesn't handle calls to base implementations in overriden methods' (and properties') decompilation. This is caused by the decompilation algorithm not tracking virtual vs concrete handling in an overriden method chain.
The solution I tried (which seems successful up to now) is to maintain a context that handles all calls to the same instance's member as concrete after the first virtual call.

I may be able to submit a clean PR soon if you'd  #prefer, but until then you can check the changes on my test branch (https://github.com/magicmoux/DelegateDecompiler/tree/FEAT-TestComplements)
The main changes are located in: 
=> MethodBodyDecompiler.DecompileConcrete method.
=> Processor.BuildMethodCall method.
I also extended the GetDeclaredMethod implementation to match both method's name and signature on the type's hierarchy

Tell me what you think about it
Max.

**Comment by hazzik** [comment]
Thanks for reporting in. I'll check these.

**Comment by magicmoux** [comment]
Ok merci.
Btw, I'd like to discuss some design possibilities about the current
library/project layout depending on your insights.

You can PM me directly at magicmoux[arobase]gmail[.]com

Le mer. 20 juin 2018 23:54, Alexander Zaytsev <notifications@github.com> a
écrit :

**Comment by hazzik** [comment]
@magicmoux I've fixed (I think) ordering of the type hierarchies. I'll deal with other issues later.

**Comment by magicmoux** [comment]
Hi @hazzik,

Could you please check PR #138 please, ?
I think publishing a new nuget would help some.

Thanks in advance,
Max.
