### ISSUE TITLE
Are interpollated strings supported?

### ISSUE THREAD

**Issue by paulvanbladel** [hazzik/DelegateDecompiler#128]
```
  [Computed]
    public string FullName
    {
        get { return $"{FirstName}  {LastName}"; }
    }
```

**Comment by hazzik** [comment]
Interpolation usually a syntactic sugar for `string.Format(...)`. The DelegateDecompiler correctly decompiles the expression, however the support of the expression would be solely dependant on the underlying linq provider for which expression tree is intended.
