### ISSUE TITLE
Specifiying CultureInfo for a ToString.

### ISSUE THREAD

**Issue by paulvanbladel** [hazzik/DelegateDecompiler#129]
Specifying a ToString(CultureInfo.InvariantCulture) seems not be accepted.
That's a pity since the default for ToString is CurrentCulture which make string operation very machine specific. So I always specify InvariantCulture for making things more robust.

BTW, this is a magic library ! Many thanks for sharing this.

**Comment by magicmoux** [comment]
Can you please send a test snippet to check this ?

Thanks,
Max.

**Comment by hazzik** [comment]
Sorry, but I'm not sure what you're trying to report here. Please provide some examples.
