### ISSUE TITLE
Anyway to make System.IO.Path.Combine work in a calculated property

### ISSUE THREAD

**Issue by aplocher** [hazzik/DelegateDecompiler#130]
Hey just discovered this project and it looks great.  I was wondering if there's a way to make the following code work:

    db.Files.Where(x => x.FilePath == filePath)

FilePath is a calculated property that is simply:

    public string FilePath => Path.Combine(DirectoryPath, FileName);

`DirectoryPath` and `FileName` are coming from EF.  EF complains about the 'FilePath' property not translating to SQL.  

If I add `[Computed]` to the property and `.Decompile()` to the end of the lambda expression it seems to get a little further, but then it complains about the `Combine` method not translating.  I tried even adding a `.Computed()` to the end of the Path.Combine but then I get a "Stack empty" `InvalidOperationException`.

Thanks

**Comment by jaenyph** [comment]
EF is telling you that it can not translate Combine to SQL. Just use the "+" concat operator and it should work.

Good luck.

From: Adam Plocher
Sent: Friday, August 3, 09:31
Subject: [hazzik/DelegateDecompiler] Anyway to make System.IO.Path.Combine work in a calculated property (#130)
To: hazzik/DelegateDecompiler
Cc: Subscribed


Hey just discovered this project and it looks great. I was wondering if there's a way to make the following code work:
db.Files.Where(x => x.FilePath == filePath)
FilePath is a calculated property that is simply:
public string FilePath => Path.Combine(DirectoryPath, FileName);
DirectoryPath and FileName are coming from EF. EF complains about the 'FilePath' property not translating to SQL.
If I add [Computed] to the property and .Decompile() to the end of the lambda expression it seems to get a little further, but then it complains about the Combine method not translating. I tried even adding a .Computed() to the end of the Path.Combine but then I get a "Stack empty" InvalidOperationException.
Thanks

**Comment by aplocher** [comment]
Ah that's the easy way... No fun... :) Thanks!
