### ISSUE TITLE
DecompileAsync in EF 6.1.3 Silently locks MVC app

### ISSUE THREAD

**Issue by IronSean** [hazzik/DelegateDecompiler#136]
I'm running into an issue with the DecompileAsync() on the DelegateDecompiler.EntityFramework package with EntityFramework 6.1.3. I haven't done a ton of investigation yet so this is mostly to see if others are seeing it or have immediate ideas.

The following synchronous code works:
```csharp
public IHttpActionResult Get(int param)
{
    var itemQuery = myService.QueryItems(param);
    var itemViewModelQuery = itemQuery.Select(ItemViewModel.AsViewModel); //An Expression
    var decompiledItemViewModelQuery = itemViewModelQuery.Decompile();
    var items = decompiledItemViewModelQuery.ToList();

    return Ok(items);
}
```

But if I do it asynchronously this does not work:
```csharp
public Task<IHttpActionResult> Get(int param)
{
    var itemQuery = myService.QueryItems(param);
    var itemViewModelQuery = itemQuery.Select(ItemViewModel.AsViewModel); //An Expression
    var decompiledItemViewModelQuery = itemViewModelQuery.DecompileAsync();
    var items = await decompiledItemViewModelQuery.ToListAsync();

    return Ok(items);
}
```

In the async case my ASP.NET MVC app actually freezes, the server will not respond to any requests and they just show as `pending` in Chrome Dev Tools. New requests and Tabs won't ever load, but Visual Studio is not frozen, shows no exceptions or errors, and can pause execution although it just states that the current thread isn't in code I can view.

**Comment by hazzik** [comment]
Sorry, there's not enough information to action this ticket.
