### ISSUE TITLE
Publish the latest version to nuget.org

### ISSUE THREAD

**Issue by derigel23** [hazzik/DelegateDecompiler#153]
DelegateDecompiler.EntityFramework and DelegateDecompiler.EntityFrameworkCore packages.

**Comment by derigel23** [comment]
More specific, DelegateDecompiler.EntityFramework  and DelegateDecompiler.EntityFrameworkCore packages.

**Comment by hazzik** [comment]
Thanks. I'll do.

**Comment by hazzik** [comment]
Publish forgotten 0.26.1 and also release 0.27.0
