### ISSUE TITLE
EF Core 3.0 compatibility

### ISSUE THREAD

**Issue by derigel23** [hazzik/DelegateDecompiler#154]
System.TypeLoadException: Method 'ExecuteAsync' in type 'DelegateDecompiler.EntityFrameworkCore.AsyncDecompiledQueryProvider' from assembly 'DelegateDecompiler.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=93b26a10a04705bd' does not have an implementation.

**Comment by hazzik** [comment]
It seems that this will require releasing a new nuget package. I'll take a look on the following week.

**Comment by derigel23** [comment]
See PR#155
