### ISSUE TITLE
Please enable netstandard2.1 profile for DelegateDecompiler.EntityFramework

### ISSUE THREAD

**Issue by dmostert** [hazzik/DelegateDecompiler#157]
As per the title.

I'm currently using a forked version to enable netstandard2.1

**Comment by hazzik** [comment]
For what particular reason? It works fine as far as tests show.

**Comment by dmostert** [comment]
I get the following warning when I use the official package:
`Warning	NU1701	Package 'DelegateDecompiler.EntityFramework 0.27.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	`

Thanks

**Comment by hazzik** [comment]
I had to update EF to 6.3 to make this work. Otherwise I was getting warnings.
