### ISSUE TITLE
ArgumentException for a simple method

### ISSUE THREAD

**Issue by AradAral** [hazzik/DelegateDecompiler#166]
@hazzik Hey there! I believe I have discovered some sort of a bug.

I have this method, which I'm attempting to decompile:
```csharp
public static CommentDto ToCommentDto(this Comment comment)
{
    return new CommentDto
    {
        HasUserPurchasedTheCourse = comment.User.Purchases.Any(p => p.Items.Any(i => i.CourseId == comment.CourseId)),
        // "p" is of type "Purchase" - "i" is of type "PurchaseItem"
    };
}
```
when I call the `Decompile()` extension method for the above method, I get the following exception:

```
System.ArgumentException: 'Expression of type 'System.Func'2[PurchaseItem,System.Boolean]' cannot be used for parameter of type 'System.Collections.Generic.IEnumerable'1[PurchaseItem]' of method 'Boolean Any[PurchaseItem](System.Collections.Generic.IEnumerable`1[PurchaseItem], System.Func'2[PurchaseItem,System.Boolean])' (Parameter 'arg0')'
```

One thing I found out is that if I change the expression `comment.CourseId` to a literal value like `1`, the exception would no longer be thrown.

Let me know if any further information is needed.

**Comment by hazzik** [comment]
Should be fixed in 0.29.0
