### ISSUE TITLE
Automatically decompile using a IDbContextOptionsExtension like LinqKit does?

### ISSUE THREAD

**Issue by bzbetty** [hazzik/DelegateDecompiler#184]
Linqkit lets you register an EF extension so that they don't need the manual Decompile() like call for each query. I think something like that would be theoretically possible with Delegate Decompiler too?

```
builder
    .UseSqlServer(connectionString)
    .WithExpressionExpanding();
```

reference: https://github.com/scottksmith95/LINQKit/blob/master/src/LinqKit.Microsoft.EntityFrameworkCore/ExpandableDbContextOptionsExtension.cs

**Comment by hazzik** [comment]
Thanks for suggestion. I'll think about this. Meanwhile. Pull request are welcomed.

**Comment by hazzik** [comment]
I've done some preliminary work. Unfortunately a new package for EF Core 6 would be required as there are some incompatible changes that I cannot make compatible between both EF Core 5 and EF Core 6.

**Comment by powermetal63** [comment]
@hazzik You can take a look at this SO answer https://stackoverflow.com/a/62138200/5202563, and especially the update for EF Core 7.0, since now thanks to the added Linq query expression interception mechanism all you need is few lines of code.
