### ISSUE TITLE
The provider for the source 'IQueryable' doesn't implement 'IAsyncQueryProvider'

### ISSUE THREAD

**Issue by ankushbbbr** [hazzik/DelegateDecompiler#242]
In .NET8 (EntityFrameworkCore 8.0.5), When I call `CountAsync()` on `IQueryable` returned by `.DecompileAsync()` function, I get this error - 
```
System.InvalidOperationException: The provider for the source 'IQueryable' doesn't implement 'IAsyncQueryProvider'. Only providers that implement 'IAsyncQueryProvider' can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)

```
where as if I call `.ToListAsync()).Count` on the same IQueryable, it works. 
Apparently, [AsyncDecompiledQueryProvider](https://github.com/hazzik/DelegateDecompiler/blob/main/src/DelegateDecompiler.EntityFramework/AsyncDecompiledQueryProvider.cs) should implement `IAsyncQueryProvider`. I don't know why it works for `ToListAsync()` and does not work for `CountAsync()` though.

**Comment by hazzik** [comment]
It does: 

https://github.com/hazzik/DelegateDecompiler/blob/33ec52f12b0c21a70369da03f1c19214cf006936/src/DelegateDecompiler.EntityFrameworkCore5/AsyncDecompiledQueryProvider.cs#L9C1-L9C115

What packages do you use?

**Comment by ankushbbbr** [comment]
DelegateDecompiler.EntityFramework 0.34.0

**Comment by ankushbbbr** [comment]
Nvm, it works fine when I changed to DelegateDecompiler.EntityFrameworkCore5 0.34.0
