### ISSUE TITLE
Problem updating DelegateDecompiler.EntityFramework

### ISSUE THREAD

**Issue by JonPSmith** [hazzik/DelegateDecompiler#44]
My local NuGet library, GenericServices, has a [Nuget .nuspec file](https://github.com/JonPSmith/GenericServices/blob/master/GenericServices/NuGet/GenericServices.nuspec) that currently references 0.13.0 version of . Now that 0.14.0 is out I wanted to update my application to that, which I do with the command `Update-Package DelegateDecompiler.EntityFramework`. However I get the error when I do that. The PM command and the resultant error is given below.

```
PM> Update-Package DelegateDecompiler.EntityFramework
Updating 'DelegateDecompiler.EntityFramework' from version '0.13.0.0' to '0.14.0' in project 'SampleMvcWebAppComplex'.
Update-Package : Unable to resolve dependency 'DelegateDecompiler (= 1.0.0.0)'.
At line:1 char:1
+ Update-Package DelegateDecompiler.EntityFramework
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
 ```

**Comment by hazzik** [comment]
I see

**Comment by hazzik** [comment]
Should be fixed now

**Comment by JonPSmith** [comment]
Yes, its fixed. Thanks for your help on that.
