### ISSUE TITLE
Compute - Include - Decompile problem

### ISSUE THREAD

**Issue by mayorovp** [hazzik/DelegateDecompiler#52]
Look at this test:

		[Test]
		public void ComputeIncludeDecompileNotFail()
		{
			using (var db = new EfTestDbContext())
			{
				db.EfParents.Where(p => ComputedSample()).Include(p => p.Children).Decompile().Load();
			}
		}

		[Computed]
		private static bool ComputedSample() { return true; }

What happens here? `Include` returns `IQueryable` with expression like `value(ObjectQuery<...>).Include("Children")`. Call of function `ComputedSample()` is hidden in constant expression and ignored by DelegateDecompiler. => EF fails to execute query.

---

Что тут происходит? Вызов `Include`возвращает `IQueryable` с выражением вроде `value(ObjectQuery<...>).Include("Children")`. Здесь вызов функции `ComputedSample()` скрыт в константном выражении - а потому игнорируется библиотекой DelegateDecompiler. Как следствие - EF не может выполнить запрос.

**Comment by mayorovp** [comment]
Maybe this issue is a duplicate of #38

**Comment by hazzik** [comment]
Duplicates #38
