### ISSUE TITLE
Can't get auto Decompile via configuration to work

### ISSUE THREAD

**Issue by esditm** [hazzik/DelegateDecompiler#55]
I'm trying to get the auto decompile to work as shown here: http://daveaglick.com/posts/computed-properties-and-entity-framework
But it doesn't work :(

Not sure what I'm doing wrong.

Here's the class that has a computed value.
```csharp
public class Person
{
	public int Id { get; set; }
	public string First { get; set; }
	public string Last { get; set; }

	[NotMapped]
	[Computed]
	public string Full { get { return First + " " + Last; } }
}
```

This is the configuration.
```csharp
public class DelegateDecompilerConfiguration : DefaultConfiguration
{
	public override bool ShouldDecompile(MemberInfo memberInfo)
	{
		// Automatically decompile all NotMapped members
		return base.ShouldDecompile(memberInfo) || memberInfo.GetCustomAttributes(typeof(NotMappedAttribute), true).Length > 0;
	}
}
```
I also tried removing the `[NotMapped]` and then changed `typeof(NotMappedAttribute)` to `typeof(ComputedAttribute)` in the above configuration.

Then I register it like so
```csharp
DelegateDecompiler.Configuration.Configure(new DelegateDecompilerConfiguration());
```
In Startup.cs. I also tried putting it directly into my action.

```csharp
public ActionResult Test()
{
	DelegateDecompiler.Configuration.Configure(new DelegateDecompilerConfiguration());

	var ctx = new ApplicationDbContext();
	var result = ctx.People.Where(x => x.Full.Contains("foo bar")).ToList();

	return View();
}
```
Neither work :(

If I put `.Decompile()` on the query then it works as expected. So the DelegateDecompiler is working, but not the configuration.

**Comment by esditm** [comment]
Also opened a stackoverflow http://stackoverflow.com/questions/31983116/cant-get-shoulddecompile-configuration-in-delegatedecompiler-to-work

**Comment by esditm** [comment]
I've come to the conclusion that I've misunderstood what the blogger meant.

> In fact, you can make it even easier to use by automatically processing NotMappedAttribute to indicate computed properties. To do this, just create a new Configuration class:

> ``` 
public class DelegateDecompilerConfiguration : DefaultConfiguration
{
    public override bool ShouldDecompile(MemberInfo memberInfo)
    {
        // Automatically decompile all NotMapped members
        return base.ShouldDecompile(memberInfo) || memberInfo.GetCustomAttributes(typeof(NotMappedAttribute), true).Length > 0;
    }
}
```

What he means is that I don't have to use the `[Computed]` attribute but can just use the `[NotMapped]` attribute.

This comment really threw me off.
> // Automatically decompile all NotMapped members

**Comment by hazzik** [comment]
Yep, that's right you need to call `.Decompile()` anyway.

**Comment by daveaglick** [comment]
I can see the confusion - I'll make the blog post clearer.
