### ISSUE TITLE
Complex expressions cause error during Merge Method in Address class

### ISSUE THREAD

**Issue by TheVscript** [hazzik/DelegateDecompiler#63]
Hi,

It seems this row throws an exception when we use Knockout.Mvc package and new version of Delegate decompiler in our application. (v17 cause error but with previous version everything works smoothly)

We want to generate ViewModel included calculated fields with Knockout.MVC and at least one of our expressions looks somethinkg like the following:
 1. address1.Expression will be null (in init phase)
 2. address2.Type is a Value Type

Therefore we get an exception in Address class in Merge method:
    
     var left = address1.Expression ?? Expression.Constant(null, address2.Type);

To resolve this I suggest to extend the Address class with a "Default" method (almost the same method defined in Process class) and use the Default(...); instead of Expression.Constant(....) everywhere:
    
    static Expression Default(Type type)    {
        //TODO QUESTION: What about Enums?
        //TODO QUESTION: Is this really necessary?
        if (type == null)
            return Expression.Constant(null, typeof(Nullable<>)); 
        if (type.IsValueType)
        {
            // LINQ to entities and possibly other providers don't support Expression.Default, so this gets the default value and then uses an Expression.Constant instead
            return Expression.Constant(Activator.CreateInstance(type), type);
        }
        return Expression.Constant(null, type);
}

**Comment by hazzik** [comment]
Hi, @thevscript, this has been fixed in December branch. This is the same as #58. I will release a new version shortly.

**Comment by TheVscript** [comment]
Good news, Thank You!
