### ISSUE TITLE
Decimal multiplication with an int wont work with Nhibernate

### ISSUE THREAD

**Issue by mwillebrands** [hazzik/DelegateDecompiler#65]
Hi,

When multiplying a decimal with an int, NHibernate crashes with "Code supposed to be unreachable" (in StackSpiller.cs inside System.Core) when compiling to a lambda. 

The difference between directly executing the code and decompiling it is as follows:
*direct*
`myClass.MyItems.Sum(item=> (item.MyDecimal* Convert(item.MyInt)))`

*decompiled*
`myClass.MyItems.Sum(item=> (item.MyDecimal* op_Implicit(item.MyInt)))`

I can do a workaround by explicitly put Convert.ToDecimal in my code, but i would like to understand why it goes wrong.

Is this a bug in DelegateDecompiler or in Nhibernate?

(kinda hard to create a testcase because Nhibernate is also needed)

There was another _bug_ but that was fixed by checking out your latest version from the repo. Same error as above, but it was caused by using op_addition instead of + with decimals. (Don't know if it is related, but i thought it was worth mentioning) DelegateDecompiler previously was doing op_addition(decimal1, decimal2) and is now doing decimal1 + decimal2.

*Looks like it's because decimal isn't a primitive type.*

**Comment by hazzik** [comment]
@mwillebrands bug is in DelegateDecompiler

**Comment by hazzik** [comment]
This has been released to nuget

**Comment by mwillebrands** [comment]
Thanks!
Op 29 dec. 2015 06:15 schreef "Alexander Zaytsev" <notifications@github.com
