### ISSUE TITLE
Support CoreCLR

### ISSUE THREAD

**Issue by jbogard** [hazzik/DelegateDecompiler#66]
I spiked this out, the biggest issue will be getting the Mono.Reflection dependency. You'd either need to switch to the MS packages or get that package updated.

**Comment by daveaglick** [comment]
:+1: I appreciate you taking the time to figure out what it would take. I use this library like crazy and it's going to end up being a blocker for moving to .NET Core on a lot of my work-related projects (though that won't even be on the table for a long while).

**Comment by hazzik** [comment]
@jbogard, probably I will internalize the Mono.Reflection or switch to some other decompiler (Roslyn/Cecil/ILSpy - not sure yet).

**Comment by hazzik** [comment]
@jbogard @daveaglick I would happily accept a pull request

**Comment by rdefreitas** [comment]
@jbogard @hazzik looks like the assembly-saver branch of Mono.Reflection has some recent changes that address issues in vNext/Core specifically. Might be able to get @jbevain to put out a new release?

**Comment by hazzik** [comment]
@rdefreitas I dont think that .NET Core has .GetMethodBody() method

**Comment by rdefreitas** [comment]
@hazzik if I'm not mistaken, GetMethodBody is internal but there is the MethodBody property of the MethodImplementation struct.

https://github.com/dotnet/corefx/blob/release/1.0.0-rc1/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MethodImplementation.cs

**Comment by jbevain** [comment]
@rdefreitas System.Reflection.Metadata is a fully managed metadata reader, it's completely separate from the traditional System.Reflection.

If .NET Core doesn't have `GetMethodBody()`, Mono.Reflection is going to be difficult to port.

**Comment by rdefreitas** [comment]
@jbevain, my apologies, it seems you're correct. I came across this issue in dotnet/corefx#4543, which mentions that .NET Native won't have access to retrieve MetadataTokens... I would assume this is the reason for the lack of GetMethodBody().

> (@nguerrera - https://github.com/dotnet/corefx/issues/4543#issuecomment-157491151 ) You can use GetMetadataToken() from System.Reflection.TypeExtensions and then drop down to System.Reflection.Metadata to get the IL. I'll post a gist later tonight. Keep in mind that tokens will not be available on .NET Native if you're also expecting this to work there. 

----

Having a windows-only version of **Mono.Reflection** would kind of defeat the purpose of even having Mono in the name. :-1:  Although, maybe having a subproject that is temporarily limited wouldn't be all bad and would at least get the ball rolling (with a delay for cross-platform functionality)...  perhaps _Mono.Reflection.CoreFx_.  @hazzik, is _DelegateDecompiler_ Mono-friendly or just using the lib?

----
Anyway, I was led down this road through a need to see @AutoMapper EF6 extensions ported to EF Core... I'm happy to contribute to make this happen, I just need to find the right starting point.

**Comment by zsvanderlaan** [comment]
I would also like to see .net core support for use with Automapper EF extensions and would be happy to help contribute if anyone can point in the right direction.

**Comment by jbogard** [comment]
@zsvanderlaan we're all waiting for .NET Standard 2.0/.NET Core 2.0 to drop. That's where GetMethodBody comes back. Then this will need to target `netstandard20`.

**Comment by zsvanderlaan** [comment]
In case anyone else is not familiar with this, i did some research, and from what I understand .net core 2.0 will run on top of .net standard 2.0, which is cross platform. .net standard 2.0 is the framework layer where GetMethodBody is defined, and so once .net standard 2.0 is released (suspected May 10th at Build) the Delegate Decompiler library (and its Mono.Reflection dependency) should be able to target .net standard 2.0 instead of the full .net framework currently being referenced.

**Comment by hazzik** [comment]
I made a PR to support .NET Standard 2.0 to Mono.Reflection: https://github.com/jbevain/mono.reflection/pull/16

**Comment by tb-mtg** [comment]
Hi guys, Are there any updates now that .NET Standard/Core 2.0 specifications are complete?

**Comment by hazzik** [comment]
@tb-mtg I'm waiting on Mono.Reflection dependency. However you can easily reference DelegateDecompiler/Mono.Reflection from .NET Standard 2.0 assembly using compatibility mode

**Comment by derigel23** [comment]
DelegateDecompiler.EntityFramework should reference Microsoft.EntityFrameworkCore for  .NET Standard/Core 2.0 or better introduce new package DelegateDecompiler.EntityFrameworkCore?

**Comment by jbogard** [comment]
New package.

**Comment by eveneveneven** [comment]
Are you still waiting for Mono.Reflection dependency? Will that even happen this year?
I'm eagerly awaiting support for EF Core :)

**Comment by hazzik** [comment]
I had to release own version of [Mono.Reflection](https://www.nuget.org/packages/Mono.Reflection.Core) to be able to proceed.

**Comment by hazzik** [comment]
I've released [DelegateDecompiler.EntityFrameworkCore](https://www.nuget.org/packages/DelegateDecompiler.EntityFrameworkCore).
