### ISSUE TITLE
Dynamic query with predicate builder doesn't decompile children computed properties.

### ISSUE THREAD

**Issue by DreadedTuba** [hazzik/DelegateDecompiler#68]
I posted this to stackoverflow a few weeks ago.  I don't know if it is an issue with DelegateDecompiler, but I was hoping someone here could resolve it.

http://stackoverflow.com/questions/34364756/how-to-use-delegatedecompiler-computed-properties-with-predicatebuilder-and-chil

**Comment by hazzik** [comment]
I will take a look

**Comment by DreadedTuba** [comment]
Thanks.  I tried looking into it, but realized I didn't know enough to debug it.

**Comment by DreadedTuba** [comment]
I found a solution with LinqKit's Expand() extension.
Adding .Expand() to the predicate resolved the exception.

**Comment by hazzik** [comment]
As I understand this is not the DelegateDecompiler issue.
