### ISSUE TITLE
Endless loop in GetJoinPoint

### ISSUE THREAD

**Issue by mwillebrands** [hazzik/DelegateDecompiler#69]
When calculating a value in a foreach loop, delegatedecompiler will get stuck in GetJoinPoint.
Doing a sum on TotalPrice in TestContainer will fail (keeps on going endlessly)

Please see the testcase: http://hastebin.com/tabijojoku.csharp

``` C#
  public class TestContainer
        {
            public List<TestItem> Items { get; set; }

            [Computed]
            public decimal TotalPrice
            {
              //  get { return this.Items.Sum(s => s.TotalPrice); } //This works

                //This causes GetJoinPoint to go in an endless loop
                get
                {
                    decimal total = 0;
                    foreach (var item in this.Items)
                    {
                        total += item.TotalPrice;
                    }
                    return total;
                }
            }
        }

        public class TestItem
        {
            public int Amount { get; set; }
            public decimal Price { get; set; }

            [Computed]
            public decimal TotalPrice
            {
                get { return this.Amount*this.Price; }
            }
        }
```

**Comment by hazzik** [comment]
Just to make this clear - there is no way to represent the loop as
expression; so this will, probably, never be supported. The loops need to
be always written as Linq functions (sum, select, aggregate, etc).

I can try to make DD to detect loops and throw appropriate exception, but
could not promise to implement this soon.

**Comment by mwillebrands** [comment]
No problem, thanks for the heads up!
