### ISSUE TITLE
Decompile fails with NullReferenceException when expression contains extension method

### ISSUE THREAD

**Issue by ykosbie** [hazzik/DelegateDecompiler#71]
DelegateDecompiler crashes with a NullReferenceException on this code

    var r = customers.Select(x => new {
        Name = x.GetFullName().Computed()
    })
    .Decompile();

where `GetFullName` is an extension method

    public static string GetFullName(this Customer c) {
        return c.FirstName + " " + c.LastName;
    }

**Comment by hazzik** [comment]
Released as 0.19.0
