### ISSUE TITLE
Decimal math is not recognized as operator

### ISSUE THREAD

**Issue by ykosbie** [hazzik/DelegateDecompiler#72]
VB compiler generates MSIL with `OpCodes.Call` to the `System.Decimal.Add`, `System.Decimal.Multiply`, etc methods for math performed on `decimal` numbers (I have not checked if C# compiler does the same).  This is not recognized as an operator by `Processor.BuildMethodCallExpression` so the resulting expression tree has `Expression.Call("Decimal.Subtract", args...)` instead of `Expression.Subtract(args...)`.

EF does not convert the decimal specific calls, only the general `Expression.Subtract`.

**Comment by hazzik** [comment]
Pushed to NuGet
