### ISSUE TITLE
Unsupported abstract and virtual properties (Perhaps and methods too).

### ISSUE THREAD

**Issue by GetRandom** [hazzik/DelegateDecompiler#76]
Hi, Alexander!
For my EF entities I use inheritance with overriding of properties in derived classes. But DelegateDecompiler ignores all overrides and uses body, which declared in the base virtual property or (in case with abstract property) throws "NullReferenceException".

As I understand, you can speak Russian. You can contact me on:
skype - vadim.ivanenko
email  - get_random@hotmail.com

**Comment by hazzik** [comment]
@GetRandom can you show some code? I was trying to reproduce this in https://github.com/hazzik/DelegateDecompiler/issues/50 but failed.

**Comment by GetRandom** [comment]
@hazzik Here is a demo project.
[https://github.com/GetRandom/demo](https://github.com/GetRandom/demo)

Briefly:
```
public abstract class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Computed]
        public abstract int SomeAbstractBusinessRule { get; }

        [Computed]
        public virtual int SomeVirtualBusinessRule
        {
            get { return 111; }
        }
    }

    public class DerivedGroup : Group
    {
        [Computed]
        public override int SomeAbstractBusinessRule
        {
            get { return 222; }
        }

        [Computed]
        public override int SomeVirtualBusinessRule
        {
            get { return 222; }
        }
    }
```

```
                // Case 1 (virtual)
                var dto = context.Groups
                    .Select(g => new GroupDto
                    {
                        Id = g.Id,
                        Name = g.Name,

                        // Expected: 222
                        // Actual: 111
                        SomeVirtualBusinessRule = g.SomeVirtualBusinessRule,
                    })
                    .Decompile()
                    .FirstOrDefault();

                // Case 2 (abstract)
                dto = context.Groups
                    .Select(g => new GroupDto
                    {
                        Id = g.Id,
                        Name = g.Name,

                        // Expected: 222
                        // Actual: NullReferenceException
                        SomeAbstractBusinessRule = g.SomeAbstractBusinessRule
                    })
                    .Decompile()
                    .FirstOrDefault();
```

**Comment by hazzik** [comment]
Probably will never be supported. Because the expression does not know the exact type of the entity, it can not make any assumptions about inheritors. 

But if you can show me the desired decompiled expression (query), I would try to implement this.

**Comment by hazzik** [comment]
The idea is to decompile method to the explicit type check-implementation:
abstract: 
```
x => x is DerivedGroup ? 222 : null;
```
virtual:
```
x => x is DerivedGroup ? 222 : 111;
```
This will require to have explicit (implicit would be expensive) configuration for abstract/virtual methods and properties.

**Comment by jaenyph** [comment]
@hazzik I think you are right, we can retrieve all the concrete classes when we are handling an override of an abstract properties, and modify the expression tree to use is/as operators. It should work as linq2entities support them.

`return x is ConcreteClassA 
  ? (x as ConcreteClassA).SomeOverrideProp 
  : x is ConcreteClassB 
    ? (x as ConcreteClassB).SomeOverrideProp
    : x is ConcreteClassC 
      ? (x as ConcreteClassC).SomeOverrideProp 
      : %default for type of SomeOverrideProp %`
