### ISSUE TITLE
Math.Round problem

### ISSUE THREAD

**Issue by EdsonMiranda** [hazzik/DelegateDecompiler#80]
I have a method that returns a Math.Round(decimalNumber, 1, MidpointRounding.AwayFromZero) and I am getting the following error:
 
> LINQ to Entities does not recognize the method 'System.Decimal Round(System.Decimal, Int32, System.MidpointRounding)' method, and this method cannot be translated into a store expression.

If I remove MidpointRounding.AwayFromZero, then it works fine.

Having problems with property DayOfWeek of DateTime fields too

**Comment by mwillebrands** [comment]
This has nothing to do with DelegateDecompiler but with Linq to Entities. There is no direct SQL statement for the function you are calling. So either you have to write it yourself or do the rounding in code where it is not translated to sql. 

Same with your other problems.

**Comment by EdsonMiranda** [comment]
Ok, thank you!
