### ISSUE TITLE
DateTime operations

### ISSUE THREAD

**Issue by EdsonMiranda** [hazzik/DelegateDecompiler#81]
Is it supported?
I am having troubles in following expression:

int daysDiff = (dateTime1 - dateTime2).Days

> DbArithmeticExpression arguments must have a numeric common type

**Comment by mwillebrands** [comment]
This has nothing to do with DelegateDecompiler. I suspect you are using EntityFramework, so you can use these functions: https://msdn.microsoft.com/en-us/library/system.data.entity.dbfunctions.aspx

**Comment by EdsonMiranda** [comment]
Ok, thank you! DbFunctions solved the problem!
