### ISSUE TITLE
vs2015

### ISSUE THREAD

**Issue by be4i** [hazzik/DelegateDecompiler#82]
Hello, when i upgraded to vs2015 now extension method Decompile() throws this error

> The binary operator GreaterThan is not defined for the types 'ClassA' and 'System.Object'

i have one computed property in ClassA that makes a simple bool expression `PropertyA != null`

**EDIT:** i know that i edited the reason a couple of times but i was testing some stuff and for sure the reason is because i build the project with vs2015

**Comment by be4i** [comment]
Can anyone give me some direction to where to look ?

**Comment by hazzik** [comment]
Please check the latest version, it's probably fixed

**Comment by be4i** [comment]
I am on the latest version publish to Nuget (0.19.0)

**Comment by be4i** [comment]
i was able to make it work with this expression `PropertyA == null ? false : true`

**Comment by hazzik** [comment]
Fixed in 9e114ff

**Comment by hazzik** [comment]
Pushed to NuGet
