### ISSUE TITLE
String concatenation throws Exception if ToString is not called explicitly

### ISSUE THREAD

**Issue by cervengoc** [hazzik/DelegateDecompiler#84]
I use version 0.18.1. I have the following simple class.

```
public class Test {
  public int A { get; set; }
  public int B { get; set; }
  
  [Computed]
  public string FromAToB => A + "-"  + B;
}
```

This throws an exception when decompiling. However, if I explicitly call `ToString` on the numbers like

```
public string FromAToB => A.ToString() + "-"  + B.ToString();
```
 
it works nicely.

On top of everything, tools like Resharper wants to remove the explicit `ToString` call, and as a result the code can crash at runtime, which all together is a terrible situation.

**Comment by hazzik** [comment]
Hey, I can not get it fail on the develop branch in VS 2015. Can you please confirm the environment you use?

**Comment by hazzik** [comment]
Ok, fixed by #70

**Comment by cervengoc** [comment]
Thank you for the quick response. Could you please put together a new NuGet release? Would be important to have this fixed.

**Comment by hazzik** [comment]
I'll do later today

**Comment by hazzik** [comment]
Released as 0.19.0

**Comment by cervengoc** [comment]
Thank you, I was checking the related changes in the code. At first glance it seemed like the fixes are only for the cases when `int` values are used within concatenation, but maybe I'm wrong. Don't have time currently for testing, so I'd like to ask if the fix covers every types, like `float`, `double`, `long`, `bool` etc.?

**Comment by hazzik** [comment]
Yes, all these cases are fixed.
