### ISSUE TITLE
Does this require the Computed Attribute?

### ISSUE THREAD

**Issue by Suamere** [hazzik/DelegateDecompiler#86]
Does this require the C# Attribute notation? [Computed]?  Or can you use the Fluent API HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed) and see the same results.

**Comment by hazzik** [comment]
Not sure that I'm follwing you on the issue

**Comment by Suamere** [comment]
Quick Response!  This isn't necessarily an issue, except that it's an issue for me if I can't do so.  My Entity Classes exist in a project where there is no Entity Framework installed.  I use the Fluent API to apply EF Properties such as DatabaseGeneratedOptions.  E.G.:

modelBuilder.Entity<Income>().Property(t => t.Sum)
    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)

So I do not put [Computed] or [DatabaseGenerated(DatabaseGeneratedOption.Computed)] above my properties in my class.  My Entities look like POCO objects.

Or, perhaps, I am confusing the Entity Framework's Computed attribute with a Computed attribute provided directly by this project...

**Comment by Suamere** [comment]
Sorry, I just scanned the code real quick and saw that you are providing your own ComputedAttribute.  I made an assumption that it was the EF Computed attribute.  I appologize.

**Comment by hazzik** [comment]
No worries. 
Yes, DD has own `ComputedAttribute`.
