### ISSUE TITLE
The method 'Skip' is only supported for sorted input in LINQ to Entities.

### ISSUE THREAD

**Issue by mellamokb** [hazzik/DelegateDecompiler#99]
Receiving the following error message when using the Decompile() method with a Kendo MVC UI:

> The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'.

I am not using the Skip or OrderBy method anywhere in the code.

`        return Json(EmpLiteRepo.GetCompanyListForSelection().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);`

The definition for GetCompanyListForSelection() is as follows:

```
        public IQueryable<CompanySelection> GetCompanyListForSelection()
        {
            try
            {
                var query = (
                from company in _getCompanyQry()
                select new CompanySelection
                   {
                       CompanyCode = company.CompanyCode,
                       CompanyName = company.CompanyNameDisplay,
                       //company.CompanyCode + " - " + company.CompanyName

                   }).Decompile();
                return query;
            }
            catch (Exception ex) { throw ex; }
        }
```

Where _getCompanyQry() is a helper function that loads permissions.  CompanyNameDisplay is a reference to property that must be decompiled and lifted.  It is working in other similar queries where it is referenced, but for some reason breaks on this one.

**Comment by hazzik** [comment]
I don't know what is `ToDataSourceResult` but I assume this is Telekrik's extension. I have to assume that it adds Skip&Take to the `IQueryable<>`. What it is saying is that you need to add default sort order to the query.

**Comment by hazzik** [comment]
Also, It seems that you are using EF, so, please use DelegateDecompiler.EntityFramework and it's `DecompileAsync` method.

**Comment by mellamokb** [comment]
I can confirm that adding an OrderBy clause to the code has resolved the error.

Thanks, hazzik!

**Comment by hazzik** [comment]
np
